"""Initial schema - workflows, conversations, agents, convergence_metrics

Revision ID: a39eb78501fd
Revises: 
Create Date: 2026-02-11 11:36:32.338037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39eb78501fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('issue_title', sa.String(length=500), nullable=False),
    sa.Column('issue_body', sa.Text(), nullable=True),
    sa.Column('issue_url', sa.String(length=500), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('issue_labels', sa.Text(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('final_convergence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_instance_id'), ['instance_id'], unique=True)
        batch_op.create_index('ix_workflows_repo_issue', ['repository', 'issue_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_status'), ['status'], unique=False)
        batch_op.create_index('ix_workflows_status_created', ['status', 'created_at'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('expertise', sa.String(length=500), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('rounds_participated', sa.Integer(), nullable=False),
    sa.Column('first_comment_round', sa.Integer(), nullable=True),
    sa.Column('last_comment_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_agents_workflow_name', ['workflow_id', 'agent_name'], unique=True)

    op.create_table('convergence_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('convergence_score', sa.Float(), nullable=False),
    sa.Column('agreement_level', sa.Float(), nullable=True),
    sa.Column('value_added', sa.Float(), nullable=True),
    sa.Column('rambling_detected', sa.Boolean(), nullable=False),
    sa.Column('value_trend', sa.String(length=50), nullable=True),
    sa.Column('comments_this_round', sa.Integer(), nullable=False),
    sa.Column('agents_participated', sa.Integer(), nullable=False),
    sa.Column('new_topics_raised', sa.Integer(), nullable=True),
    sa.Column('should_continue', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convergence_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convergence_metrics_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_convergence_workflow_round', ['workflow_id', 'round_number'], unique=True)

    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('github_comment_id', sa.Integer(), nullable=True),
    sa.Column('should_comment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_history_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_history_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_conversation_workflow_round', ['workflow_id', 'round_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_workflow_round')
        batch_op.drop_index(batch_op.f('ix_conversation_history_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_history_agent_name'))

    op.drop_table('conversation_history')
    with op.batch_alter_table('convergence_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_convergence_workflow_round')
        batch_op.drop_index(batch_op.f('ix_convergence_metrics_workflow_id'))

    op.drop_table('convergence_metrics')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('ix_agents_workflow_name')
        batch_op.drop_index(batch_op.f('ix_agents_workflow_id'))

    op.drop_table('agents')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index('ix_workflows_status_created')
        batch_op.drop_index(batch_op.f('ix_workflows_status'))
        batch_op.drop_index('ix_workflows_repo_issue')
        batch_op.drop_index(batch_op.f('ix_workflows_instance_id'))

    op.drop_table('workflows')
    # ### end Alembic commands ###
